# output for command: sed -i -e 's/trvaep\.utils/\.\.utils/g' trvaep/model/helper_module.py &&  /apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip install --prefix=/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/trvaep/0.1.0-foss-2022a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .

Processing /tmp/vsc43810/easybuild/build/trvaep/0.1.0/foss-2022a/trvaep/trvaep-0.1.0
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
   Preparing metadata (pyproject.toml) did not run successfully.
   exit code: 1
  > [24 lines of output]
      Traceback (most recent call last):
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
          metadata = make_metadata(module, ini_info)
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/flit_core/common.py", line 408, in make_metadata
          md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/flit_core/common.py", line 205, in get_info_from_module
          docstring, version = get_docstring_and_version_via_import(target)
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/flit_core/common.py", line 178, in get_docstring_and_version_via_import
          spec.loader.exec_module(m)
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/vsc43810/easybuild/build/trvaep/0.1.0/foss-2022a/trvaep/trvaep-0.1.0/trvaep/__init__.py", line 3, in <module>
          from .model import *
        File "/tmp/vsc43810/easybuild/build/trvaep/0.1.0/foss-2022a/trvaep/trvaep-0.1.0/trvaep/model/__init__.py", line 2, in <module>
          from .train import Trainer
        File "/tmp/vsc43810/easybuild/build/trvaep/0.1.0/foss-2022a/trvaep/trvaep-0.1.0/trvaep/model/train.py", line 7, in <module>
          from trvaep.model._losses import MSE_kl, mmd
      ModuleNotFoundError: No module named 'trvaep'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

 Encountered error while generating package metadata.
> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
